name: Docker

on:
    push:
        branches: [master]

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - context: ./8.0-apache
                      tag: 8.0-apache

                    - context: ./8.1-apache
                      tag: 8.1-apache

            fail-fast: false

        name: Docker (reinerttomas/php:${{ matrix.tag }})

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: ${{ matrix.context }}
                push: true
                tags: reinerttomas/php:${{ matrix.tag }}
                platforms: linux/amd64,linux/arm64